site_name: Polyatomic Complexes - Documentation (v1.0.8)
site_url: https://sitename.example
theme:
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
  name: material
  font:
    text: 'Roboto'
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/logo.ico
  palette:
    - scheme: 'slate'
      toggle:
        icon: 'material/weather-sunny'
        name: 'Dark mode'
      primary: 'blue'
      accent: 'yellow'
    - scheme: 'default'
      toggle:
        icon: 'material/weather-night'
        name: Light mode
      primary: 'blue'
      accent: 'yellow'

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      pygments_style: "solarized-light"
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

copyright: '© 2024 Rahul Khorana'

