name: CI

on:
 - push:
 - pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
        
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run tests
        run: pytest
      
      - name: mypy
        run: mypy
      
      - name: flake8
        run: flake8
