name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.11.6']
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip' # caching pip dependencies
          lfs: true
      - run: git lfs pull
      - run: pip install -r requirements.txt
      
      - name: run tests
        working-directory: .
        run: python -B -m pytest -v
      
